<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite8942bdc72982da6a140f91c7311fb32
{
    public static $prefixLengthsPsr4 = array (
        'K' =>
        array (
            'KrokedilKlarnaPaymentsDeps\\Krokedil\\WpApi\\' => 42,
            'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\' => 48,
            'KrokedilKlarnaPaymentsDeps\\Krokedil\\Support\\' => 44,
            'KrokedilKlarnaPaymentsDeps\\Krokedil\\SignInWithKlarna\\' => 53,
            'KrokedilKlarnaPaymentsDeps\\Krokedil\\SettingsPage\\' => 49,
            'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOrderManagement\\' => 58,
            'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOnsiteMessaging\\' => 58,
            'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\' => 58,
            'KrokedilKlarnaPaymentsDeps\\Firebase\\JWT\\' => 40,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WpApi\\' =>
        array (
            0 => __DIR__ . '/..' . '/krokedil/wp-api/src',
        ),
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\' =>
        array (
            0 => __DIR__ . '/..' . '/krokedil/woocommerce/src',
        ),
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\Support\\' =>
        array (
            0 => __DIR__ . '/..' . '/krokedil/support/src',
        ),
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SignInWithKlarna\\' =>
        array (
            0 => __DIR__ . '/..' . '/krokedil/sign-in-with-klarna/src',
        ),
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SettingsPage\\' =>
        array (
            0 => __DIR__ . '/..' . '/krokedil/settings-page/src',
        ),
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOrderManagement\\' =>
        array (
            0 => __DIR__ . '/..' . '/krokedil/klarna-order-management/src',
        ),
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOnsiteMessaging\\' =>
        array (
            0 => __DIR__ . '/..' . '/krokedil/klarna-onsite-messaging/src',
        ),
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\' =>
        array (
            0 => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src',
        ),
        'KrokedilKlarnaPaymentsDeps\\Firebase\\JWT\\' =>
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'KrokedilKlarnaPaymentsDeps\\Firebase\\JWT\\BeforeValidException' => __DIR__ . '/..' . '/firebase/php-jwt/src/BeforeValidException.php',
        'KrokedilKlarnaPaymentsDeps\\Firebase\\JWT\\CachedKeySet' => __DIR__ . '/..' . '/firebase/php-jwt/src/CachedKeySet.php',
        'KrokedilKlarnaPaymentsDeps\\Firebase\\JWT\\ExpiredException' => __DIR__ . '/..' . '/firebase/php-jwt/src/ExpiredException.php',
        'KrokedilKlarnaPaymentsDeps\\Firebase\\JWT\\JWK' => __DIR__ . '/..' . '/firebase/php-jwt/src/JWK.php',
        'KrokedilKlarnaPaymentsDeps\\Firebase\\JWT\\JWT' => __DIR__ . '/..' . '/firebase/php-jwt/src/JWT.php',
        'KrokedilKlarnaPaymentsDeps\\Firebase\\JWT\\JWTExceptionWithPayloadInterface' => __DIR__ . '/..' . '/firebase/php-jwt/src/JWTExceptionWithPayloadInterface.php',
        'KrokedilKlarnaPaymentsDeps\\Firebase\\JWT\\Key' => __DIR__ . '/..' . '/firebase/php-jwt/src/Key.php',
        'KrokedilKlarnaPaymentsDeps\\Firebase\\JWT\\SignatureInvalidException' => __DIR__ . '/..' . '/firebase/php-jwt/src/SignatureInvalidException.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\AJAX' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/AJAX.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\Api\\Controllers\\Notifications' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/Api/Controllers/Notifications.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\Api\\Notifications\\Handler' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/Api/Notifications/Handler.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\Api\\Notifications\\NotificationsProvider' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/Api/Notifications/NotificationsProvider.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\Api\\Notifications\\PaymentStateCompleted' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/Api/Notifications/PaymentStateCompleted.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\Api\\Notifications\\PaymentStateExpired' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/Api/Notifications/PaymentStateExpired.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\Assets' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/Assets.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\Blocks\\OneStepBlocksIntegration' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/Blocks/OneStepBlocksIntegration.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\ClientTokenParser' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/ClientTokenParser.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\Interfaces\\AcquiringPartnerIntegration' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/Interfaces/AcquiringPartnerIntegration.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\KlarnaExpressCheckout' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/KlarnaExpressCheckout.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\OneStepCheckout' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/OneStepCheckout.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\Requests' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/Requests.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\Requests\\Base' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/Requests/Base.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\Requests\\Notification\\CreateSigningKey' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/Requests/Notification/CreateSigningKey.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\Requests\\Notification\\CreateWebhook' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/Requests/Notification/CreateWebhook.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\Requests\\Notification\\DeleteSigningKey' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/Requests/Notification/DeleteSigningKey.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\Requests\\Notification\\DeleteWebhook' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/Requests/Notification/DeleteWebhook.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\Requests\\Notification\\SimulateWebhook' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/Requests/Notification/SimulateWebhook.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\Session' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/Session.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\Settings' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/Settings.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaExpressCheckout\\WebhookSetup' => __DIR__ . '/..' . '/krokedil/klarna-express-checkout/src/WebhookSetup.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOnsiteMessaging\\Blocks\\CartBlockIntegration' => __DIR__ . '/..' . '/krokedil/klarna-onsite-messaging/src/Blocks/CartBlockIntegration.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOnsiteMessaging\\KlarnaOnsiteMessaging' => __DIR__ . '/..' . '/krokedil/klarna-onsite-messaging/src/KlarnaOnsiteMessaging.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOnsiteMessaging\\Pages\\Cart' => __DIR__ . '/..' . '/krokedil/klarna-onsite-messaging/src/Pages/Cart.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOnsiteMessaging\\Pages\\Page' => __DIR__ . '/..' . '/krokedil/klarna-onsite-messaging/src/Pages/Page.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOnsiteMessaging\\Pages\\Product' => __DIR__ . '/..' . '/krokedil/klarna-onsite-messaging/src/Pages/Product.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOnsiteMessaging\\Settings' => __DIR__ . '/..' . '/krokedil/klarna-onsite-messaging/src/Settings.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOnsiteMessaging\\Shortcode' => __DIR__ . '/..' . '/krokedil/klarna-onsite-messaging/src/Shortcode.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOnsiteMessaging\\Utility' => __DIR__ . '/..' . '/krokedil/klarna-onsite-messaging/src/Utility.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOnsiteMessaging\\Widget' => __DIR__ . '/..' . '/krokedil/klarna-onsite-messaging/src/Widget.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOrderManagement\\Ajax' => __DIR__ . '/..' . '/krokedil/klarna-order-management/src/Ajax.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOrderManagement\\KlarnaOrderManagement' => __DIR__ . '/..' . '/krokedil/klarna-order-management/src/KlarnaOrderManagement.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOrderManagement\\Logger' => __DIR__ . '/..' . '/krokedil/klarna-order-management/src/Logger.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOrderManagement\\MetaBox' => __DIR__ . '/..' . '/krokedil/klarna-order-management/src/MetaBox.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOrderManagement\\OrderLines' => __DIR__ . '/..' . '/krokedil/klarna-order-management/src/OrderLines.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOrderManagement\\PendingOrders' => __DIR__ . '/..' . '/krokedil/klarna-order-management/src/PendingOrders.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOrderManagement\\Request\\Get\\RequestGetOrder' => __DIR__ . '/..' . '/krokedil/klarna-order-management/src/Request/Get/RequestGetOrder.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOrderManagement\\Request\\Patch\\RequestPatchUpdate' => __DIR__ . '/..' . '/krokedil/klarna-order-management/src/Request/Patch/RequestPatchUpdate.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOrderManagement\\Request\\Post\\RequestPostCancel' => __DIR__ . '/..' . '/krokedil/klarna-order-management/src/Request/Post/RequestPostCancel.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOrderManagement\\Request\\Post\\RequestPostCapture' => __DIR__ . '/..' . '/krokedil/klarna-order-management/src/Request/Post/RequestPostCapture.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOrderManagement\\Request\\Post\\RequestPostRefund' => __DIR__ . '/..' . '/krokedil/klarna-order-management/src/Request/Post/RequestPostRefund.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOrderManagement\\Request\\Request' => __DIR__ . '/..' . '/krokedil/klarna-order-management/src/Request/Request.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOrderManagement\\Request\\RequestGet' => __DIR__ . '/..' . '/krokedil/klarna-order-management/src/Request/RequestGet.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOrderManagement\\Request\\RequestPatch' => __DIR__ . '/..' . '/krokedil/klarna-order-management/src/Request/RequestPatch.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOrderManagement\\Request\\RequestPost' => __DIR__ . '/..' . '/krokedil/klarna-order-management/src/Request/RequestPost.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOrderManagement\\ScheduledActions' => __DIR__ . '/..' . '/krokedil/klarna-order-management/src/ScheduledActions.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOrderManagement\\SellersApp' => __DIR__ . '/..' . '/krokedil/klarna-order-management/src/SellersApp.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOrderManagement\\Settings' => __DIR__ . '/..' . '/krokedil/klarna-order-management/src/Settings.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\KlarnaOrderManagement\\Utility' => __DIR__ . '/..' . '/krokedil/klarna-order-management/src/Utility.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SettingsPage\\Addons' => __DIR__ . '/..' . '/krokedil/settings-page/src/Addons.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SettingsPage\\Gateway' => __DIR__ . '/..' . '/krokedil/settings-page/src/Gateway.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SettingsPage\\Navigation' => __DIR__ . '/..' . '/krokedil/settings-page/src/Navigation.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SettingsPage\\Page' => __DIR__ . '/..' . '/krokedil/settings-page/src/Page.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SettingsPage\\SettingsPage' => __DIR__ . '/..' . '/krokedil/settings-page/src/SettingsPage.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SettingsPage\\Support' => __DIR__ . '/..' . '/krokedil/settings-page/src/Support.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SettingsPage\\Traits\\Layout' => __DIR__ . '/..' . '/krokedil/settings-page/src/Traits/Layout.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SettingsPage\\Traits\\Sidebar' => __DIR__ . '/..' . '/krokedil/settings-page/src/Traits/Sidebar.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SettingsPage\\Traits\\Singleton' => __DIR__ . '/..' . '/krokedil/settings-page/src/Traits/Singleton.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SettingsPage\\Traits\\Subsection' => __DIR__ . '/..' . '/krokedil/settings-page/src/Traits/Subsection.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SignInWithKlarna\\AJAX' => __DIR__ . '/..' . '/krokedil/sign-in-with-klarna/src/AJAX.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SignInWithKlarna\\JWT' => __DIR__ . '/..' . '/krokedil/sign-in-with-klarna/src/JWT.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SignInWithKlarna\\Redirect' => __DIR__ . '/..' . '/krokedil/sign-in-with-klarna/src/Redirect.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SignInWithKlarna\\Settings' => __DIR__ . '/..' . '/krokedil/sign-in-with-klarna/src/Settings.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SignInWithKlarna\\SignInWithKlarna' => __DIR__ . '/..' . '/krokedil/sign-in-with-klarna/src/SignInWithKlarna.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\SignInWithKlarna\\User' => __DIR__ . '/..' . '/krokedil/sign-in-with-klarna/src/User.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\Support\\Logger' => __DIR__ . '/..' . '/krokedil/support/src/Logger.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\Support\\SystemReport' => __DIR__ . '/..' . '/krokedil/support/src/SystemReport.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Base' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Base.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Cart\\Cart' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/Cart.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Cart\\CartCustomer' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/CartCustomer.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Cart\\CartLineCoupon' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/CartLineCoupon.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Cart\\CartLineFee' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/CartLineFee.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Cart\\CartLineItem' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/CartLineItem.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Cart\\CartLineShipping' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Cart/CartLineShipping.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Compatibility\\Abstracts\\AbstractGiftCardCompatibility' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Abstracts/AbstractGiftCardCompatibility.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Compatibility\\Compatibility' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Compatibility.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Compatibility\\Giftcards\\PWGiftCards' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Giftcards/PWGiftCards.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Compatibility\\Giftcards\\SmartCoupons' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Giftcards/SmartCoupons.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Compatibility\\Giftcards\\WCGiftCards' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Giftcards/WCGiftCards.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Compatibility\\Giftcards\\YITHGiftCards' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Compatibility/Giftcards/YITHGiftCards.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\CustomerData' => __DIR__ . '/..' . '/krokedil/woocommerce/src/CustomerData.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Interfaces\\CompatibilityInterface' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Interfaces/CompatibilityInterface.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Interfaces\\GiftCardCompatibilityInterface' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Interfaces/GiftCardCompatibilityInterface.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Interfaces\\MetaboxInterface' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Interfaces/MetaboxInterface.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\KrokedilWooCommerce' => __DIR__ . '/..' . '/krokedil/woocommerce/src/KrokedilWooCommerce.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\OrderData' => __DIR__ . '/..' . '/krokedil/woocommerce/src/OrderData.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\OrderLineData' => __DIR__ . '/..' . '/krokedil/woocommerce/src/OrderLineData.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\OrderMetabox' => __DIR__ . '/..' . '/krokedil/woocommerce/src/OrderMetabox.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\OrderUtility' => __DIR__ . '/..' . '/krokedil/woocommerce/src/OrderUtility.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Order\\Order' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/Order.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Order\\OrderCustomer' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderCustomer.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Order\\OrderLine' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderLine.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Order\\OrderLineCoupon' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderLineCoupon.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Order\\OrderLineFee' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderLineFee.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Order\\OrderLineItem' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderLineItem.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Order\\OrderLineShipping' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Order/OrderLineShipping.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApi' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApi.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiCustomer' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApiCustomer.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiLineCoupon' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApiLineCoupon.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiLineFee' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApiLineFee.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiLineItem' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApiLineItem.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\StoreApi\\StoreApiLineShipping' => __DIR__ . '/..' . '/krokedil/woocommerce/src/StoreApi/StoreApiLineShipping.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WooCommerce\\Subscription' => __DIR__ . '/..' . '/krokedil/woocommerce/src/Subscription.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WpApi\\Logger' => __DIR__ . '/..' . '/krokedil/wp-api/src/Logger.php',
        'KrokedilKlarnaPaymentsDeps\\Krokedil\\WpApi\\Request' => __DIR__ . '/..' . '/krokedil/wp-api/src/Request.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite8942bdc72982da6a140f91c7311fb32::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite8942bdc72982da6a140f91c7311fb32::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInite8942bdc72982da6a140f91c7311fb32::$classMap;

        }, null, ClassLoader::class);
    }
}
